fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      # Disabling the fix-encoding-pragma because UTF-8 is assumed for Python 3
      # - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: name-tests-test
      - id: pretty-format-json
        args: ["--autofix"]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
      - id: check-added-large-files
    # files: ^(?!(templates/)).*
  # - repo: https://github.com/PyCQA/flake8
  #   rev: v4.0.1
  #   hooks:
  #     - id: flake8
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.5
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
  # - repo: https://github.com/psf/black
  #   rev: 23.11.0
  #   hooks:
  #     - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.941
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports']
  # - repo: https://github.com/FalconSocial/pre-commit-mirrors-pep257
  #   rev: v0.3.3 # Use the sha / tag you want to point at
  #   hooks:
  #     - id: pep257
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  # - repo: https://github.com/pycqa/isort
  #   rev: v5.10.1
  #   hooks:
  #     - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/asottile/dead
    rev: v1.4.0
    hooks:
      - id: dead
        args: ['--exclude', 'templates/validation/']
  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.3'  # or any later Vulture version
    hooks:
      - id: vulture
  - repo:  https://github.com/milin/giticket
    rev: v1.3
    hooks:
    - id:  giticket
  - repo:  https://github.com/PyCQA/docformatter
    rev: v1.4
    hooks:
    - id: docformatter
      name: docformatter
      description: 'Formats docstrings to follow PEP 257.'
      entry: docformatter
      args: [-i]
      language: python
      types: [python]
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.2
    hooks:
    - id: editorconfig-checker
      alias: ec
  - repo: https://github.com/dannysepler/rm_unneeded_f_str
    rev: v0.1.0
    hooks:
    - id: rm-unneeded-f-str
  # - repo: https://github.com/hadialqattan/pycln
  #   rev: v0.0.1-beta.3
  #   hooks:
  #     - id: pycln
  #       args: [--config=pyproject.toml]
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.5.4
  #   hooks:
  #     - id: isort
  #       files: "\\.(py)$"
  #       args: [--settings-path=pyproject.toml]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
    - id: python-bandit-vulnerability-check
      args: [--verbose, -ll, --skip, "B321,B402", --recursive, src]
